version: '3'
services:
  mysql:
    image: 'mysql-server:8.0'
    restart: always
    container_name: BigOps_mysql
    build: .
    volumes:
      - ./data:/var/lib/mysql
      - ./mysql/config/my.cnf:/etc/my.cnf
      - ./mysql/init:/docker-entrypoint-initdb.d/
      # 数据库还原目录 可将需要还原的sql文件放在这里
      #- /home/dockerdata/mysql/source:docker-entrypoint-initdb.d
    environment:
      - "MYSQL_ROOT_PASSWORD=yunwei3322"
      - "MYSQL_DATABASE=mysql"
      - "TZ=Asia/Shanghai"
    ports:
      - 13306:3306
volumes:
  data:
    driver: local