version: '3'
services:
  db:
    restart: always
    image: mysql/rebuild:5.7
    container_name: mysql_5.7
    privileged: true  # 解决可能出现创建文件的权限问题
    build: ./
    ports:
      - 13306:3306
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=yunwei3322
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M
      --sql-mode="STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION,NO_ZERO_DATE,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO"
    volumes:
      - /home/dockerdata/mysql/data:/var/lib/mysql
      - /home/dockerdata/mysql/config:/etc/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d/